### ISSUE TITLE
[week 2] algorithm problem solving

### ISSUE THREAD

**Issue by jeeyn** [jeeyn/goorm-study-eleven#1]
## 2주차 알고리즘 문제 풀이

* 2023년 12월 4일 ~ 2023년 12월 10일

* 강의 시청 : 그리디 알고리즘 & 구현 유형 (12강 ~ 15강)
  * https://www.youtube.com/playlist?list=PLRx0vPvlEmdAghTr5mXQxGpHjWqSz0dgC

* **각 이슈 Assignees에 자신의 GitHub 계정을 추가**

* 3문제 이상 풀이 후 아래 Comment 업로드 하여 인증
  * `ex`
[Baekjoon online judge] 10828. 스택 / 실버 4
https://github.com/jeeyn/algorithm/blob/main/Baekjoon/Silver/BOJ_10828.java

**Comment by HyemCha** [comment]
- 백준 1343
https://github.com/HyemCha/algorithm-study/blob/main/python_algorithm/Greedy/boj_1343.py
- 백준 13305
https://github.com/HyemCha/algorithm-study/blob/main/python_algorithm/Greedy/boj_13305.py

**Comment by 1haann** [comment]
- [Bronze III] 전자레인지 - 10162
https://github.com/SeWoong-Han/Algorithm/tree/master/%EB%B0%B1%EC%A4%80/Bronze/10162.%E2%80%85%EC%A0%84%EC%9E%90%EB%A0%88%EC%9D%B8%EC%A7%80

- [Silver III] 주유소 - 13305
https://github.com/SeWoong-Han/Algorithm/blob/master/%EB%B0%B1%EC%A4%80/Silver/13305.%E2%80%85%EC%A3%BC%EC%9C%A0%EC%86%8C/%EC%A3%BC%EC%9C%A0%EC%86%8C.java

- [Gold IV] 단어 수학 - 1339
https://github.com/SeWoong-Han/Algorithm/blob/master/%EB%B0%B1%EC%A4%80/Gold/1339.%E2%80%85%EB%8B%A8%EC%96%B4%E2%80%85%EC%88%98%ED%95%99/%EB%8B%A8%EC%96%B4%E2%80%85%EC%88%98%ED%95%99.java

**Comment by jeeyn** [comment]
* 이코테 2021 Greedy Exercise 01 ~ 03
https://github.com/jeeyn/algorithm/tree/main/%EC%9D%B4%EC%BD%94%ED%85%8C%202021%20with%20Python

* 프로그래머스 Lv.1 체육복
https://github.com/jeeyn/algorithm/blob/main/Programmers/Pro_lv-1_42862.java
