### ISSUE TITLE
[project] plan-brainstorming

### ISSUE THREAD

**Issue by jeeyn** [jeeyn/goorm-study-eleven#6]
#### ⛳️ 팀 프로젝트 진행을 위한 아이디어를 제안해주세요

* 다음 회의 전일까지 업로드 (~ 2024. 1. 4. 23:59)

* 개인별 1개 이상 기획 후 아래 Comment 작성

  1. 팀 이름 제안
  
  2. 개발하고 싶은 웹/앱의 주요 기능 간단히 작성

**Comment by jeeyn** [comment]
`양식`

## 팀 이름 제안
- 팀명
- 의미

`ex`
> eleven
> 열한 번째 스터디 팀이자, 1등이 되자는 강한 의지를 담아(?) 1이 두 번 들어간 eleven을 팀명으로 정함

## 프로젝트 제안
- 개요
- 주요 기능 등

`ex`
> ### 위치 기반의 운동 시설 안내 웹 앱
> #### 주요 기능
> 1. 사용자 위치 기반으로 주변에 위치한 운동 관련 시설 위치 표출
> 2. 해당 시설 이용에 대한 세부 안내 (이용 시간, 주차, 운동 장비 대여 여부 등)
> 3. 주변 맛집도 안내해주면 좋을 듯
> 4. ...

**Comment by Jhsysng** [comment]
## 프로젝트 제안

>### 그룹 단위 앨범 공유방
>**주요기능**
> 1. 개인 앨범 + 그룹 공유 기능을 합친 서비스
> 2. 지도에 사진 표시
> 3. 사진 태그 기능

**Comment by HyemCha** [comment]
### 프로젝트 제안

>### 1.혼자 여행하는 사람들을 위한 밥친구 구하는 어플 
- 혼자 여행을 하다보면 식당에서 혼밥하는 사람들을 거절할 수 있음. 따라서 밥친구를 구해서 같이 식사할 수 있는 서비스를 제공해 혼자 여행하는 사람들도 관광지 식당에서 거부당하지 않을 수 있도록 한다.

- 주요 기능
    - 지도에 혼밥 거부/혼밥 가능 식당 표시해주기
    - 지도에 근처에 있는 혼자 여행하는 사람들(유저) 표시
    - 유저가 혼밥 가능 식당 등록할 수 있게 하기
    - 채팅기능
    - 사용자 평가 지수 보여주기(당근마켓 유저 온도 참고)
    - 맛집 추천
    - 게시글 crud
    - 로그인/회원가입(sns 간편 회원가입/로그인)

**Comment by jeeyn** [comment]
## 팀 이름 제안
- elevring
- 의미 : eleven + spring

## 프로젝트 제안
### 스포츠 커뮤니티

#### 주요 기능
- 생활 스포츠 카테고리 중심의 SNS
  - ex. 러닝, 축구, 테니스, 베드민턴 등
- 회원가입 / 로그인 / 로그아웃
- 팀원 / 용병 모집
- 매치 모집
- 스포츠 경기 같이 보기 모집
  - 스포츠 경기 일정 및 결과 api 연동
  - ref. https://rapidapi.com/category/Sports
+ 위치 기반 체육 시설 정보 제공 (필요시)

**Comment by jeeyn** [comment]
**1/8(월) 회의 내용 정리**

## 그룹 단위 앨범 공유 SNS
공유 앨범 기반 그룹 SNS

**주요 기능**
* 회원가입 / 로그인
    * SNS 연동 추후 고려
* 그룹 생성 후 그룹별 사진 공유
* 찍은 위치 기반으로 지도 UI 표출
* 사진 업로드 시 일시 / 장소 / 키워드 태그 정보 입력
    * 키워드 태그 자동 생성 고려
* 사진 검색
    * 일시 / 장소 / 키워드 검색
* 그룹 검색
    * 그룹명 / 참여자 검색

**고려 사항**
* 모바일 중심의 화면 구성

<br/>

## 밥 친구 구하기
* 혼밥하는 사람들을 거절하는 식당이 종종 있음
* 같이 식사할 수 있도록 밥 친구를 구하는 서비스를 제공

**주요 기능**
* 회원가입 / 로그인
    * SNS 연동 추후 고려
* 지도에 식당 위치 기반 표출
    * 맛집 추천 (구글 / 카카오 별점 데이터 기반)
* 밥 친구 구하는 게시글 CRUD
    * 게시글에 댓글 입력
* 지도에 게시글 위치 기반 표출
    * 식당 위치 또는 만나는 위치
* 유저 간 채팅
* 유저가 식당 정보 추가 입력
    * 혼밥 가능 여부, 애완견 출입 가능 여부 등
    * ex. #혼밥가능 #혼밥불가 #애완견출입가능 #애완견출입불가
* 식당 검색
    * 식당명 / 장소 / 메뉴 / 태그
* 위험 사용자 관리자에게 신고
